spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema-users.sql,classpath:db/schema-ledger.sql,classpath:db/schema-budgets.sql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:h2:mem:smartfinance;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: none
  batch:
    jdbc:
      initialize-schema: always
